-- ClickHouse DDL for SNIFF pipeline (generated from integration.schema.py).
-- Single source of truth: integration/schema.py -> integration/clickhouse_sink.py
-- DO NOT hand-edit column types here; regenerate via:
--   .venv/bin/python - <<'PY'
--   from integration.schema import FAMILIES, all_table_columns
--   ...
--   PY
--
-- 7 flows_<family> tables share the same column set (the union of all
-- per-family feature columns). Each table is ReplacingMergeTree ordered by
-- (segment_id, ts) so re-processing the same segment does not double-count.
CREATE DATABASE IF NOT EXISTS network_ids;
USE network_ids;
CREATE TABLE IF NOT EXISTS network_ids.flows_dos (
  `ts` DateTime64(3),
  `segment_id` String,
  `attack_family` LowCardinality(String),
  `attack_subtype` LowCardinality(String),
  `is_attack` UInt8,
  `interface` LowCardinality(String),
  `t_window` LowCardinality(String),
  `pcap_file` String,
  `src_mac` String DEFAULT '',
  `dst_mac` String DEFAULT '',
  `srcip` String DEFAULT '',
  `dstip` String DEFAULT '',
  `sport` Int64 DEFAULT 0,
  `dport` Int64 DEFAULT 0,
  `ltime` Int64 DEFAULT 0,
  `sttl` Int64 DEFAULT 0,
  `ct_state_ttl` Int64 DEFAULT 0,
  `dttl` Int64 DEFAULT 0,
  `sbytes` Int64 DEFAULT 0,
  `dbytes` Int64 DEFAULT 0,
  `smean` Int64 DEFAULT 0,
  `dmean` Int64 DEFAULT 0,
  `dur` Float64 DEFAULT 0,
  `spkts` Int64 DEFAULT 0,
  `dpkts` Int64 DEFAULT 0,
  `sloss` Int64 DEFAULT 0,
  `dloss` Int64 DEFAULT 0,
  `tcprtt` Float64 DEFAULT 0,
  `synack` Float64 DEFAULT 0,
  `ackdat` Float64 DEFAULT 0,
  `rate` Float64 DEFAULT 0,
  `sload` Float64 DEFAULT 0,
  `dload` Float64 DEFAULT 0,
  `ct_srv_src` Int64 DEFAULT 0,
  `ct_srv_dst` Int64 DEFAULT 0,
  `ct_dst_src_ltm` Int64 DEFAULT 0,
  `ct_src_dport_ltm` Int64 DEFAULT 0,
  `ct_dst_sport_ltm` Int64 DEFAULT 0,
  `ct_src_ltm` Int64 DEFAULT 0,
  `ct_dst_ltm` Int64 DEFAULT 0,
  `ct_flw_http_mthd` Int64 DEFAULT 0,
  `trans_depth` Int64 DEFAULT 0,
  `response_body_len` Int64 DEFAULT 0,
  `proto` String DEFAULT '',
  `state` String DEFAULT '',
  `service` String DEFAULT '',
  `analysis_score` Int64 DEFAULT 0,
  `exploits_score` Int64 DEFAULT 0,
  `fuzzers_score` Int64 DEFAULT 0,
  `generic_score` Int64 DEFAULT 0,
  `reconnaissance_score` Int64 DEFAULT 0,
  `shellcode_score` Int64 DEFAULT 0,
  `predicted_class` String DEFAULT ''
) ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMMDD(ts)
ORDER BY (segment_id, srcip, dstip, sport, dport, proto, ts)
TTL toDateTime(ts) + INTERVAL 14 DAY;
CREATE TABLE IF NOT EXISTS network_ids.flows_exploits (
  `ts` DateTime64(3),
  `segment_id` String,
  `attack_family` LowCardinality(String),
  `attack_subtype` LowCardinality(String),
  `is_attack` UInt8,
  `interface` LowCardinality(String),
  `t_window` LowCardinality(String),
  `pcap_file` String,
  `src_mac` String DEFAULT '',
  `dst_mac` String DEFAULT '',
  `srcip` String DEFAULT '',
  `dstip` String DEFAULT '',
  `sport` Int64 DEFAULT 0,
  `dport` Int64 DEFAULT 0,
  `ltime` Int64 DEFAULT 0,
  `sttl` Int64 DEFAULT 0,
  `ct_state_ttl` Int64 DEFAULT 0,
  `dttl` Int64 DEFAULT 0,
  `sbytes` Int64 DEFAULT 0,
  `dbytes` Int64 DEFAULT 0,
  `smean` Int64 DEFAULT 0,
  `dmean` Int64 DEFAULT 0,
  `dur` Float64 DEFAULT 0,
  `spkts` Int64 DEFAULT 0,
  `dpkts` Int64 DEFAULT 0,
  `sloss` Int64 DEFAULT 0,
  `dloss` Int64 DEFAULT 0,
  `tcprtt` Float64 DEFAULT 0,
  `synack` Float64 DEFAULT 0,
  `ackdat` Float64 DEFAULT 0,
  `rate` Float64 DEFAULT 0,
  `sload` Float64 DEFAULT 0,
  `dload` Float64 DEFAULT 0,
  `ct_srv_src` Int64 DEFAULT 0,
  `ct_srv_dst` Int64 DEFAULT 0,
  `ct_dst_src_ltm` Int64 DEFAULT 0,
  `ct_src_dport_ltm` Int64 DEFAULT 0,
  `ct_dst_sport_ltm` Int64 DEFAULT 0,
  `ct_src_ltm` Int64 DEFAULT 0,
  `ct_dst_ltm` Int64 DEFAULT 0,
  `ct_flw_http_mthd` Int64 DEFAULT 0,
  `trans_depth` Int64 DEFAULT 0,
  `response_body_len` Int64 DEFAULT 0,
  `proto` String DEFAULT '',
  `state` String DEFAULT '',
  `service` String DEFAULT '',
  `analysis_score` Int64 DEFAULT 0,
  `exploits_score` Int64 DEFAULT 0,
  `fuzzers_score` Int64 DEFAULT 0,
  `generic_score` Int64 DEFAULT 0,
  `reconnaissance_score` Int64 DEFAULT 0,
  `shellcode_score` Int64 DEFAULT 0,
  `predicted_class` String DEFAULT ''
) ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMMDD(ts)
ORDER BY (segment_id, srcip, dstip, sport, dport, proto, ts)
TTL toDateTime(ts) + INTERVAL 14 DAY;
CREATE TABLE IF NOT EXISTS network_ids.flows_fuzzers (
  `ts` DateTime64(3),
  `segment_id` String,
  `attack_family` LowCardinality(String),
  `attack_subtype` LowCardinality(String),
  `is_attack` UInt8,
  `interface` LowCardinality(String),
  `t_window` LowCardinality(String),
  `pcap_file` String,
  `src_mac` String DEFAULT '',
  `dst_mac` String DEFAULT '',
  `srcip` String DEFAULT '',
  `dstip` String DEFAULT '',
  `sport` Int64 DEFAULT 0,
  `dport` Int64 DEFAULT 0,
  `ltime` Int64 DEFAULT 0,
  `sttl` Int64 DEFAULT 0,
  `ct_state_ttl` Int64 DEFAULT 0,
  `dttl` Int64 DEFAULT 0,
  `sbytes` Int64 DEFAULT 0,
  `dbytes` Int64 DEFAULT 0,
  `smean` Int64 DEFAULT 0,
  `dmean` Int64 DEFAULT 0,
  `dur` Float64 DEFAULT 0,
  `spkts` Int64 DEFAULT 0,
  `dpkts` Int64 DEFAULT 0,
  `sloss` Int64 DEFAULT 0,
  `dloss` Int64 DEFAULT 0,
  `tcprtt` Float64 DEFAULT 0,
  `synack` Float64 DEFAULT 0,
  `ackdat` Float64 DEFAULT 0,
  `rate` Float64 DEFAULT 0,
  `sload` Float64 DEFAULT 0,
  `dload` Float64 DEFAULT 0,
  `ct_srv_src` Int64 DEFAULT 0,
  `ct_srv_dst` Int64 DEFAULT 0,
  `ct_dst_src_ltm` Int64 DEFAULT 0,
  `ct_src_dport_ltm` Int64 DEFAULT 0,
  `ct_dst_sport_ltm` Int64 DEFAULT 0,
  `ct_src_ltm` Int64 DEFAULT 0,
  `ct_dst_ltm` Int64 DEFAULT 0,
  `ct_flw_http_mthd` Int64 DEFAULT 0,
  `trans_depth` Int64 DEFAULT 0,
  `response_body_len` Int64 DEFAULT 0,
  `proto` String DEFAULT '',
  `state` String DEFAULT '',
  `service` String DEFAULT '',
  `analysis_score` Int64 DEFAULT 0,
  `exploits_score` Int64 DEFAULT 0,
  `fuzzers_score` Int64 DEFAULT 0,
  `generic_score` Int64 DEFAULT 0,
  `reconnaissance_score` Int64 DEFAULT 0,
  `shellcode_score` Int64 DEFAULT 0,
  `predicted_class` String DEFAULT ''
) ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMMDD(ts)
ORDER BY (segment_id, srcip, dstip, sport, dport, proto, ts)
TTL toDateTime(ts) + INTERVAL 14 DAY;
CREATE TABLE IF NOT EXISTS network_ids.flows_generic (
  `ts` DateTime64(3),
  `segment_id` String,
  `attack_family` LowCardinality(String),
  `attack_subtype` LowCardinality(String),
  `is_attack` UInt8,
  `interface` LowCardinality(String),
  `t_window` LowCardinality(String),
  `pcap_file` String,
  `src_mac` String DEFAULT '',
  `dst_mac` String DEFAULT '',
  `srcip` String DEFAULT '',
  `dstip` String DEFAULT '',
  `sport` Int64 DEFAULT 0,
  `dport` Int64 DEFAULT 0,
  `ltime` Int64 DEFAULT 0,
  `sttl` Int64 DEFAULT 0,
  `ct_state_ttl` Int64 DEFAULT 0,
  `dttl` Int64 DEFAULT 0,
  `sbytes` Int64 DEFAULT 0,
  `dbytes` Int64 DEFAULT 0,
  `smean` Int64 DEFAULT 0,
  `dmean` Int64 DEFAULT 0,
  `dur` Float64 DEFAULT 0,
  `spkts` Int64 DEFAULT 0,
  `dpkts` Int64 DEFAULT 0,
  `sloss` Int64 DEFAULT 0,
  `dloss` Int64 DEFAULT 0,
  `tcprtt` Float64 DEFAULT 0,
  `synack` Float64 DEFAULT 0,
  `ackdat` Float64 DEFAULT 0,
  `rate` Float64 DEFAULT 0,
  `sload` Float64 DEFAULT 0,
  `dload` Float64 DEFAULT 0,
  `ct_srv_src` Int64 DEFAULT 0,
  `ct_srv_dst` Int64 DEFAULT 0,
  `ct_dst_src_ltm` Int64 DEFAULT 0,
  `ct_src_dport_ltm` Int64 DEFAULT 0,
  `ct_dst_sport_ltm` Int64 DEFAULT 0,
  `ct_src_ltm` Int64 DEFAULT 0,
  `ct_dst_ltm` Int64 DEFAULT 0,
  `ct_flw_http_mthd` Int64 DEFAULT 0,
  `trans_depth` Int64 DEFAULT 0,
  `response_body_len` Int64 DEFAULT 0,
  `proto` String DEFAULT '',
  `state` String DEFAULT '',
  `service` String DEFAULT '',
  `analysis_score` Int64 DEFAULT 0,
  `exploits_score` Int64 DEFAULT 0,
  `fuzzers_score` Int64 DEFAULT 0,
  `generic_score` Int64 DEFAULT 0,
  `reconnaissance_score` Int64 DEFAULT 0,
  `shellcode_score` Int64 DEFAULT 0,
  `predicted_class` String DEFAULT ''
) ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMMDD(ts)
ORDER BY (segment_id, srcip, dstip, sport, dport, proto, ts)
TTL toDateTime(ts) + INTERVAL 14 DAY;
CREATE TABLE IF NOT EXISTS network_ids.flows_analysis (
  `ts` DateTime64(3),
  `segment_id` String,
  `attack_family` LowCardinality(String),
  `attack_subtype` LowCardinality(String),
  `is_attack` UInt8,
  `interface` LowCardinality(String),
  `t_window` LowCardinality(String),
  `pcap_file` String,
  `src_mac` String DEFAULT '',
  `dst_mac` String DEFAULT '',
  `srcip` String DEFAULT '',
  `dstip` String DEFAULT '',
  `sport` Int64 DEFAULT 0,
  `dport` Int64 DEFAULT 0,
  `ltime` Int64 DEFAULT 0,
  `sttl` Int64 DEFAULT 0,
  `ct_state_ttl` Int64 DEFAULT 0,
  `dttl` Int64 DEFAULT 0,
  `sbytes` Int64 DEFAULT 0,
  `dbytes` Int64 DEFAULT 0,
  `smean` Int64 DEFAULT 0,
  `dmean` Int64 DEFAULT 0,
  `dur` Float64 DEFAULT 0,
  `spkts` Int64 DEFAULT 0,
  `dpkts` Int64 DEFAULT 0,
  `sloss` Int64 DEFAULT 0,
  `dloss` Int64 DEFAULT 0,
  `tcprtt` Float64 DEFAULT 0,
  `synack` Float64 DEFAULT 0,
  `ackdat` Float64 DEFAULT 0,
  `rate` Float64 DEFAULT 0,
  `sload` Float64 DEFAULT 0,
  `dload` Float64 DEFAULT 0,
  `ct_srv_src` Int64 DEFAULT 0,
  `ct_srv_dst` Int64 DEFAULT 0,
  `ct_dst_src_ltm` Int64 DEFAULT 0,
  `ct_src_dport_ltm` Int64 DEFAULT 0,
  `ct_dst_sport_ltm` Int64 DEFAULT 0,
  `ct_src_ltm` Int64 DEFAULT 0,
  `ct_dst_ltm` Int64 DEFAULT 0,
  `ct_flw_http_mthd` Int64 DEFAULT 0,
  `trans_depth` Int64 DEFAULT 0,
  `response_body_len` Int64 DEFAULT 0,
  `proto` String DEFAULT '',
  `state` String DEFAULT '',
  `service` String DEFAULT '',
  `analysis_score` Int64 DEFAULT 0,
  `exploits_score` Int64 DEFAULT 0,
  `fuzzers_score` Int64 DEFAULT 0,
  `generic_score` Int64 DEFAULT 0,
  `reconnaissance_score` Int64 DEFAULT 0,
  `shellcode_score` Int64 DEFAULT 0,
  `predicted_class` String DEFAULT ''
) ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMMDD(ts)
ORDER BY (segment_id, srcip, dstip, sport, dport, proto, ts)
TTL toDateTime(ts) + INTERVAL 14 DAY;
CREATE TABLE IF NOT EXISTS network_ids.flows_reconnaissance (
  `ts` DateTime64(3),
  `segment_id` String,
  `attack_family` LowCardinality(String),
  `attack_subtype` LowCardinality(String),
  `is_attack` UInt8,
  `interface` LowCardinality(String),
  `t_window` LowCardinality(String),
  `pcap_file` String,
  `src_mac` String DEFAULT '',
  `dst_mac` String DEFAULT '',
  `srcip` String DEFAULT '',
  `dstip` String DEFAULT '',
  `sport` Int64 DEFAULT 0,
  `dport` Int64 DEFAULT 0,
  `ltime` Int64 DEFAULT 0,
  `sttl` Int64 DEFAULT 0,
  `ct_state_ttl` Int64 DEFAULT 0,
  `dttl` Int64 DEFAULT 0,
  `sbytes` Int64 DEFAULT 0,
  `dbytes` Int64 DEFAULT 0,
  `smean` Int64 DEFAULT 0,
  `dmean` Int64 DEFAULT 0,
  `dur` Float64 DEFAULT 0,
  `spkts` Int64 DEFAULT 0,
  `dpkts` Int64 DEFAULT 0,
  `sloss` Int64 DEFAULT 0,
  `dloss` Int64 DEFAULT 0,
  `tcprtt` Float64 DEFAULT 0,
  `synack` Float64 DEFAULT 0,
  `ackdat` Float64 DEFAULT 0,
  `rate` Float64 DEFAULT 0,
  `sload` Float64 DEFAULT 0,
  `dload` Float64 DEFAULT 0,
  `ct_srv_src` Int64 DEFAULT 0,
  `ct_srv_dst` Int64 DEFAULT 0,
  `ct_dst_src_ltm` Int64 DEFAULT 0,
  `ct_src_dport_ltm` Int64 DEFAULT 0,
  `ct_dst_sport_ltm` Int64 DEFAULT 0,
  `ct_src_ltm` Int64 DEFAULT 0,
  `ct_dst_ltm` Int64 DEFAULT 0,
  `ct_flw_http_mthd` Int64 DEFAULT 0,
  `trans_depth` Int64 DEFAULT 0,
  `response_body_len` Int64 DEFAULT 0,
  `proto` String DEFAULT '',
  `state` String DEFAULT '',
  `service` String DEFAULT '',
  `analysis_score` Int64 DEFAULT 0,
  `exploits_score` Int64 DEFAULT 0,
  `fuzzers_score` Int64 DEFAULT 0,
  `generic_score` Int64 DEFAULT 0,
  `reconnaissance_score` Int64 DEFAULT 0,
  `shellcode_score` Int64 DEFAULT 0,
  `predicted_class` String DEFAULT ''
) ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMMDD(ts)
ORDER BY (segment_id, srcip, dstip, sport, dport, proto, ts)
TTL toDateTime(ts) + INTERVAL 14 DAY;
CREATE TABLE IF NOT EXISTS network_ids.flows_shellcode (
  `ts` DateTime64(3),
  `segment_id` String,
  `attack_family` LowCardinality(String),
  `attack_subtype` LowCardinality(String),
  `is_attack` UInt8,
  `interface` LowCardinality(String),
  `t_window` LowCardinality(String),
  `pcap_file` String,
  `src_mac` String DEFAULT '',
  `dst_mac` String DEFAULT '',
  `srcip` String DEFAULT '',
  `dstip` String DEFAULT '',
  `sport` Int64 DEFAULT 0,
  `dport` Int64 DEFAULT 0,
  `ltime` Int64 DEFAULT 0,
  `sttl` Int64 DEFAULT 0,
  `ct_state_ttl` Int64 DEFAULT 0,
  `dttl` Int64 DEFAULT 0,
  `sbytes` Int64 DEFAULT 0,
  `dbytes` Int64 DEFAULT 0,
  `smean` Int64 DEFAULT 0,
  `dmean` Int64 DEFAULT 0,
  `dur` Float64 DEFAULT 0,
  `spkts` Int64 DEFAULT 0,
  `dpkts` Int64 DEFAULT 0,
  `sloss` Int64 DEFAULT 0,
  `dloss` Int64 DEFAULT 0,
  `tcprtt` Float64 DEFAULT 0,
  `synack` Float64 DEFAULT 0,
  `ackdat` Float64 DEFAULT 0,
  `rate` Float64 DEFAULT 0,
  `sload` Float64 DEFAULT 0,
  `dload` Float64 DEFAULT 0,
  `ct_srv_src` Int64 DEFAULT 0,
  `ct_srv_dst` Int64 DEFAULT 0,
  `ct_dst_src_ltm` Int64 DEFAULT 0,
  `ct_src_dport_ltm` Int64 DEFAULT 0,
  `ct_dst_sport_ltm` Int64 DEFAULT 0,
  `ct_src_ltm` Int64 DEFAULT 0,
  `ct_dst_ltm` Int64 DEFAULT 0,
  `ct_flw_http_mthd` Int64 DEFAULT 0,
  `trans_depth` Int64 DEFAULT 0,
  `response_body_len` Int64 DEFAULT 0,
  `proto` String DEFAULT '',
  `state` String DEFAULT '',
  `service` String DEFAULT '',
  `analysis_score` Int64 DEFAULT 0,
  `exploits_score` Int64 DEFAULT 0,
  `fuzzers_score` Int64 DEFAULT 0,
  `generic_score` Int64 DEFAULT 0,
  `reconnaissance_score` Int64 DEFAULT 0,
  `shellcode_score` Int64 DEFAULT 0,
  `predicted_class` String DEFAULT ''
) ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMMDD(ts)
ORDER BY (segment_id, srcip, dstip, sport, dport, proto, ts)
TTL toDateTime(ts) + INTERVAL 14 DAY;
CREATE TABLE IF NOT EXISTS network_ids.flows_all AS network_ids.flows_dos ENGINE = Merge(network_ids, '^flows_(dos|exploits|fuzzers|generic|analysis|reconnaissance|shellcode)$');
CREATE TABLE IF NOT EXISTS network_ids.pipeline_runs (
  run_id UUID,
  segment_id String,
  started_at DateTime,
  finished_at DateTime,
  total_flows UInt64,
  dos UInt64,
  exploits UInt64,
  fuzzers UInt64,
  generic UInt64,
  analysis UInt64,
  reconnaissance UInt64,
  shellcode UInt64,
  duration_sec Float32,
  status Enum8('running'=1,'success'=2,'failed'=3),
  error_msg String DEFAULT ''
) ENGINE = MergeTree ORDER BY started_at;
